export const sample_foods: any[] = [
	{
		id: '1',
		name: 'Пепперони пицца',
		cookTime: '10-20',
		price: 75,
		favorite: false,
		origins: ['Сыр Моцарелла, салями'],
		stars: 4.5,
		imageUrl: 'assets/food-1.jpg',
		tags: ['FastFood', 'Pizza', 'Lunch'],
	},
	{
		id: '2',
		name: 'Люля-кабоб сочный',
		price: 54,
		cookTime: '20-30',
		favorite: true,
		origins: ['Фарш говяжий'],
		stars: 4.7,
		imageUrl: 'assets/food-2.jpg',
		tags: ['SlowFood', 'Lunch'],
	},
	{
		id: '3',
		name: 'Гамбургер плюс',
		price: 26,
		cookTime: '10-15',
		favorite: false,
		origins: ['С говяжей котлетой'],
		stars: 3.5,
		imageUrl: 'assets/food-3.jpg',
		tags: ['FastFood', 'Hamburger'],
	},
	{
		id: '4',
		name: 'Картофель фри',
		price: 29,
		cookTime: '15-20',
		favorite: true,
		origins: ['Большая порция, соус'],
		stars: 3.3,
		imageUrl: 'assets/food-4.jpg',
		tags: ['FastFood', 'Fries'],
	},
	{
		id: '5',
		name: 'Куриный суп',
		price: 38,
		cookTime: '40-50',
		favorite: false,
		origins: ['Бройлерная курица'],
		stars: 3.0,
		imageUrl: 'assets/food-5.jpg',
		tags: ['SlowFood', 'Soup'],
	},
	{
		id: '6',
		name: 'Вегетарианская пицца',
		price: 89,
		cookTime: '40-50',
		favorite: false,
		origins: ['Овощи, грибы, сыр Моцарелла'],
		stars: 4.0,
		imageUrl: 'assets/food-6.jpg',
		tags: ['FastFood', 'Pizza', 'Lunch'],
	},
];

export const sample_tags: any[] = [
  { name: 'Все', count: 6 },
  { name: 'Фастфуд', count: 4 },
  { name: 'Пиццы', count: 2 },
  { name: 'Обед', count: 3 },
  { name: 'Горячее', count: 2 },
  { name: 'Бургеры', count: 1 },
  { name: 'Фри', count: 1 },
  { name: 'Супы', count: 1 },
];